spring:
  application:
    name: weather-service
  jackson:
    default-property-inclusion: non_null
  cache:
    jcache:
      config: classpath:ehcache-default.xml


  main:
    allow-bean-definition-overriding: true

  profiles:
    active: "local"

swagger:
  application:
    description: Weather Product Microservice
    version: 2.0.2-BETA
    apikey: ${openweather_apikey}


---

spring:
  profiles: local


management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      influx:
        enabled: false



