spring:
  application:
    name: weather-service
  jackson:
    default-property-inclusion: non_null


  main:
    allow-bean-definition-overriding: true

  profiles:
    active: "local"

swagger:
  application:
    description: Weather Product Microservice
    version: 0.11
    apikey: ${openweather_apikey}

apiInterface:
  key: GGG


---

spring:
  profiles: local


management:
  info:
    git:
      mode: full
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      influx:
        enabled: false



